### ISSUE TITLE
Отзыв по проекту

### ISSUE THREAD

**Issue by RichCake** [Aldar0809/calc#1]
Привет. Я проверяю твой проект.
README:

1. Инструкция запуска проекта неверная. Неправильный путь в go run. А также нет инструкции по скачиванию, но это ладно
2. Не хватает оформления. Почитай, как красиво обернуть код и команды

По коду:

1. Не получилось запустить main. Выдает ошибку импорта `calc`
2. На неправильную скобочную последовательность и деление на ноль выдает 500, а не 422
3. От калькулятора ошибки со смыслом, а от сервера просто invalid expression. Видимо ты хотел соответствовать условию, так что не засчитываю за минус
4. Разделение на папки непонятное, хочется видеть как в уроках: internal, pkg, cmd. И зачем тебе два go.mod

Нету тестов :( Целых 20 баллов приходится из-за этого снимать. Добавь минимум хотя бы.

Главное, за что я снял баллы, это тесты и нерабочий main. Исправь это и получишь много баллов

**Comment by TheFirstPy** [comment]
> Привет. Я проверяю твой проект. README:
> 
> 1. Инструкция запуска проекта неверная. Неправильный путь в go run. А также нет инструкции по скачиванию, но это ладно
> 2. Не хватает оформления. Почитай, как красиво обернуть код и команды
> 
> По коду:
> 
> 1. Не получилось запустить main. Выдает ошибку импорта `calc`
> 2. На неправильную скобочную последовательность и деление на ноль выдает 500, а не 422
> 3. От калькулятора ошибки со смыслом, а от сервера просто invalid expression. Видимо ты хотел соответствовать условию, так что не засчитываю за минус
> 4. Разделение на папки непонятное, хочется видеть как в уроках: internal, pkg, cmd. И зачем тебе два go.mod
> 
> Нету тестов :( Целых 20 баллов приходится из-за этого снимать. Добавь минимум хотя бы.
> 
> Главное, за что я снял баллы, это тесты и нерабочий main. Исправь это и получишь много баллов

![Screenshot_2024-12-23-16-04-03-59_21da60175e70af211acc4f26191b7a77](https://github.com/user-attachments/assets/49346fac-cc03-435a-a656-405cb5493b63)
Доброго времени суток! Я ценю, что вы проверили мою работу и написали мне. В качестве тестов я в README.md добавил примеры использования с командой Invoke-RestMethod. А насчёт того, что при делении на ноль выдает ошибку 500. Я несколько раз прочитал условие и на момент написания программы, почему-то подумал, что нужно ошибку 500 выдавать в этом случае. Но сейчас я смотрю на условие и не понимаю свое действие. Я просто убрал деление на ноль из условия специально. Я это исправлю

**Comment by RichCake** [comment]
По поводу деления на ноль, это мелочи. 

Самое обидное, что проект не запустился "из коробки", это портит впечатление, а критерии оценки у нас субъективные. 

Invoke-RestMethod в качестве тестов не годится. Давай чтобы не прям 0 ставить, я 3 балла дам, но это не дело. Тестов добавь 3 случая и уже хорошо будет.

Если сложно переделать структуру папок, то не заморачивайся. Просто у тебя ошибки импорта и может это связанно с тем, что у тебя зачем-то два `go.mod`. 

Итог больше всего снял за тесты и за нерабочий код. Остальное описано выше

**Comment by TheFirstPy** [comment]
Посмотрите ещё раз проект, если не затруднит. Я большинство исправил ошибок

> По поводу деления на ноль, это мелочи.
> 
> Самое обидное, что проект не запустился "из коробки", это портит впечатление, а критерии оценки у нас субъективные.
> 
> Invoke-RestMethod в качестве тестов не годится. Давай чтобы не прям 0 ставить, я 3 балла дам, но это не дело. Тестов добавь 3 случая и уже хорошо будет.
> 
> Если сложно переделать структуру папок, то не заморачивайся. Просто у тебя ошибки импорта и может это связанно с тем, что у тебя зачем-то два `go.mod`.
> 
> Итог больше всего снял за тесты и за нерабочий код. Остальное описано выше

**Comment by RichCake** [comment]
Все отлично 👍 . Поставил 98 баллов.

1. В ридми в gitclone ссылка без https и соотвественно не работает. Минус балл
2. По структуре проекта все-таки приделживайся материалов курса: internal, pkg, cmd. [материал](https://github.com/golang-standards/project-layout/tree/master). Но поставлю максимум за этот пункт, потому что я добрый :)
3. Исправил деление на ноль, но в ридми все еще 500 (еще минус балл):
<img width="869" alt="Снимок экрана 2024-12-23 в 18 59 29" src="https://github.com/user-attachments/assets/cb34c9d2-26b5-4401-97ab-efec13ded2d0" />

Как будто остальное все ок. Исправь два недочета и будет 💯. А могло быть 60, если не исправил бы

**Comment by RichCake** [comment]
Увидел, что исправил. Но не понял, почему ты здесь этого не написал. Поставил баллы 👍

**Comment by TheFirstPy** [comment]
Извиняюсь, забыл написать.
